project:
    machine_name: bltd8
    prefix: BLT
    human_name: 'BLTed 8'
    profile:
        name: lightning
    local:
        protocol: http
        hostname: '${project.machine_name}.dev'
git:
    default_branch: master
    remotes:
        - 'd8sess@svn-5767.devcloud.hosting.acquia.com:d8sess.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null

